In [2]:
#LABA2
import numpy as np

УПРАЖНЕНИЕ 1

In [ ]:
#сделать с перемножением матриц
import numpy as np
import time
import matplotlib.pyplot as plt

def python(size_of_vec):
    start = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [2*X[i]**2 + 4*Y[i] for i in range(len(X)) ]
    return time.time() - start

def numpy(size_of_vec):
    start = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = 2*X**2 + 4*Y
    return time.time() - start

def date():
    X = []
    Y = []
    y = 0
    for i in range(0, 1000, 1):
        for f in range(0, 20):
            y += (python(i) - numpy(i))        
        X.append(i)
        Y.append(y/20)
        y = 0
    return plt.plot(X, Y)

date()
plt.show()

In [ ]:
import numpy as np
import time
import matplotlib.pyplot as plt

def numpy(size_of_vec):
    start = time.time()
    X = np.random.random((50, 10))
    Y = np.random.random((10, 30))
    Z = np.dot(X, Y)
    return time.time() - start

def python(size_of_vec):
    start = time.time()
    X = 
    Y = 
    return time.time() - start

def date():
    X = []
    Y = []
    y = 0
    for i in range(0, 1000, 1):
        for f in range(0, 20):
            y += (python(i) - numpy(i))        
        X.append(i)
        Y.append(y/20)
        y = 0
    return plt.plot(X, Y)

date()
plt.show()

УПРАЖНЕНИЕ 2

In [2]:
a = np.arange(1, 80)
print(a, '\n')

bool_idx = (a%2 != 0)
print(a[bool_idx])

a[bool_idx] = -1
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79] 

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79]
[-1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20 -1 22 -1 24
 -1 26 -1 28 -1 30 -1 32 -1 34 -1 36 -1 38 -1 40 -1 42 -1 44 -1 46 -1 48
 -1 50 -1 52 -1 54 -1 56 -1 58 -1 60 -1 62 -1 64 -1 66 -1 68 -1 70 -1 72
 -1 74 -1 76 -1 78 -1]


In [3]:
УПРАЖНЕНИЕ 3

SyntaxError: invalid syntax (<ipython-input-3-b38a57e90972>, line 1)

In [4]:
c = np.arange(6).reshape((3, 2))
#print(c)

In [5]:
np.reshape(c, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
np.reshape(np.ravel(c), (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
np.reshape(c, (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [8]:
np.reshape(np.ravel(c, order='F'), (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [9]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [10]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

УПРАЖНЕНИЕ 4

In [12]:
#Создать случаую квадратную матрицу случайного размера от 10 до 100.
#Найти максимум и сумму элементов.
#Поделить каждый элемент на максимум.
#Отнять от каждой строки матрицы среднее по строке
#Заменить максимальное значение на -1.
import random
size = random.randint(10,100)
a = np.random.random((size,size))
print(a, '\n')

print(np.sum(a))
max_ = np.max(a)
print(max_)

a /= max_
print(a)

midd = np.mean(a, axis = 1, keepdims = True)
a -= midd

print(a)

[[0.30033714 0.83525176 0.17945284 0.02665728 0.40783836 0.46957885
  0.58344601 0.14646815 0.17890399 0.70706553 0.34050611 0.21409473
  0.12040873 0.50180319 0.16617203 0.42973223 0.68651153 0.86841008
  0.66690192 0.13575421]
 [0.53203186 0.23538223 0.11896351 0.92502496 0.49303399 0.85130398
  0.72523216 0.62185772 0.82106521 0.35162218 0.14001118 0.91312353
  0.98295219 0.96505806 0.13200192 0.41294988 0.2949165  0.57743942
  0.07091245 0.81133176]
 [0.12053755 0.18161977 0.07364359 0.26328815 0.66807072 0.80234037
  0.91999505 0.05106583 0.19440772 0.20617007 0.65283618 0.99354587
  0.3187744  0.03484468 0.57211631 0.30788091 0.99171281 0.87306895
  0.79245991 0.39458173]
 [0.0699507  0.3870578  0.25046773 0.38391605 0.90849205 0.33347508
  0.32457577 0.28865382 0.85967559 0.39857809 0.55687827 0.33810924
  0.31741959 0.66287018 0.12388156 0.06940096 0.07612051 0.58439508
  0.52653627 0.7542657 ]
 [0.05960636 0.60967835 0.19200418 0.547482   0.74155395 0.95442038
  0.27214789 0.1

УПРАЖНЕНИЕ 5

In [13]:
import numpy as np
np.savetxt('probuem.txt', a)
b = np.loadtxt('probuem.txt')
b

array([[-0.09813942,  0.43793227, -0.2192852 , -0.37241128,  0.00959434,
         0.07146837,  0.18558184, -0.25234124, -0.21983524,  0.30946876,
        -0.05788356, -0.18456838, -0.27845703,  0.10376242, -0.23259474,
         0.03153556,  0.2888703 ,  0.47116232,  0.26921827, -0.26307836],
       [-0.01681517, -0.31410648, -0.43077703,  0.37702801, -0.0558974 ,
         0.30314757,  0.17680304,  0.073205  ,  0.27284339, -0.19761509,
        -0.40968383,  0.36510084,  0.43508054,  0.41714771, -0.41771041,
        -0.13615474, -0.25444343,  0.02869061, -0.47893202,  0.26308888],
       [-0.3508678 , -0.28965345, -0.39786319, -0.20780842,  0.19784974,
         0.33240982,  0.450319  , -0.42048979, -0.27683784, -0.26505005,
         0.18258224,  0.52402891, -0.15220215, -0.43674603,  0.10168777,
        -0.16311919,  0.52219189,  0.40329139,  0.32250799, -0.07623083],
       [-0.34152245, -0.02372942, -0.16061495, -0.02687797,  0.49883274,
        -0.07742804, -0.08634661, -0.12234625,  

УПРАЖНЕНИЕ 6

In [17]:
a = np.random.random(10)
print(a)
value = input()

indices = np.abs(a - value)
result_ = argmin(indices)
print(a[result_])

[0.21680446 0.34485976 0.96120482 0.79047281 0.39244539 0.14923855
 0.15102986 0.75998449 0.65004534 0.39198826]


 0.3


TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')