In [5]:
#LABA2
import numpy as np

#Ex2
a = np.arange(2, 76)
print(a, '\n')

b = a[1::2]
print(b, '\n')

for i in range(len(b)):
    b[i] = -1
print(b)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75] 

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53 55 57 59 61 63 65 67 69 71 73 75] 

[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


In [11]:
#Ex3

c = np.arange(6).reshape((3, 2))
#print(c)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
np.reshape(c, (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
np.reshape(np.ravel(c), (2, 3))

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
np.reshape(c, (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [17]:
np.reshape(np.ravel(c, order='F'), (2, 3), order='F')

array([[0, 4, 3],
       [2, 1, 5]])

In [20]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)

array([1, 2, 3, 4, 5, 6])

In [19]:
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

In [41]:
#Ex4
#Создать случаую квадратную матрицу случайного размера от 10 до 100.
#Найти максимум и сумму элементов.
#Поделить каждый элемент на максимум.
#Отнять от каждой строки матрицы среднее по строке
#Заменить максимальное значение на -1.
size = rm.randint(10,15)
a = np.zeros((size, size))
for i in range(size):
    for j in range(size):
        a[i,j] = rm.randint(0,10)
print(a, '\n')

print(np.sum(a))
max_ = np.max(a)
print(max_)

a /= max_
print(a)

a = np.reshape(a, (size, size))
for i in range(size):
    sum_ = 0
    for j in range(size):
        sum_ += a[i,j]
    for j in range(size):
        a[i,j] -= sum_/size
        #print(sum_/size)
print(a, '\n')

for i in range(size):
    for j in range(size):
        if a[i,j] == max_:
            a[i,j] = -1
print(a)

[[ 3.  0. 10.  1.  9.  7.  1.  9.  6.  9.  3.  8.  1.]
 [ 8.  3.  6.  1.  6.  0. 10.  7.  6.  9.  6.  5.  4.]
 [ 2.  2.  7.  2.  0.  7.  2.  8.  2.  1.  7.  1.  0.]
 [ 4.  6.  3. 10.  7.  5.  0.  0.  6.  5.  6.  0.  2.]
 [ 3.  3.  3.  2. 10.  0.  5.  4. 10.  7. 10.  5.  1.]
 [ 8.  7.  6.  1.  3.  7. 10.  8.  6.  8.  5.  9.  3.]
 [10. 10.  1.  0.  8.  1.  8.  1. 10.  6.  5. 10.  0.]
 [ 9.  4.  3.  5.  7.  5. 10. 10.  8.  0.  6.  2.  0.]
 [ 3.  8.  7.  6.  4.  4.  0.  9.  4. 10.  6.  4.  9.]
 [ 8.  0.  0.  5.  1.  7.  9.  2.  9.  2.  5.  1.  2.]
 [ 7.  4.  6.  4.  9.  2.  9.  1.  0.  8.  0.  3.  9.]
 [ 3.  2.  5. 10.  8.  3.  6.  1.  9.  5.  9.  7.  1.]
 [ 4.  2.  7.  4.  0.  1.  4.  3.  5.  5.  3.  1.  5.]] 

816.0
10.0
[[0.3 0.  1.  0.1 0.9 0.7 0.1 0.9 0.6 0.9 0.3 0.8 0.1]
 [0.8 0.3 0.6 0.1 0.6 0.  1.  0.7 0.6 0.9 0.6 0.5 0.4]
 [0.2 0.2 0.7 0.2 0.  0.7 0.2 0.8 0.2 0.1 0.7 0.1 0. ]
 [0.4 0.6 0.3 1.  0.7 0.5 0.  0.  0.6 0.5 0.6 0.  0.2]
 [0.3 0.3 0.3 0.2 1.  0.  0.5 0.4 1.  0.7 1.  0.5 0